<a href="https://colab.research.google.com/github/amrKidwai/Ecommerce-Funnel-Analysis/blob/main/Project_1_Ecommerce_Funnel_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1, Generate Real Dataset

In [1]:
from numpy.random.mtrand import f
import pandas as pd
import numpy as np

np.random.seed(42)

n = 1000

df = pd.DataFrame({
    'user_id': np.arange(1, n+1),
    'visit_date': pd.date_range(start='2024-01-01', periods=n, freq='h'),
    'device': np.random.choice(['mobile', 'desktop'], n, p=[0.7, 0.3]),
    'added_to_cart': np.random.choice([0,1], n, p=[0.4, 0.6]),
})

df['purchased'] = df['added_to_cart'] * np.random.choice([0,1], n, p=[0.5, 0.5])
df['revenue'] = df['purchased'] * np.random.randint(100, 2000, n)

df.to_csv('ecommerce_data.csv', index=False)


df.head()

   user_id          visit_date   device  added_to_cart  purchased  revenue
0        1 2024-01-01 00:00:00   mobile              0          0        0
1        2 2024-01-01 01:00:00  desktop              1          0        0
2        3 2024-01-01 02:00:00  desktop              1          1      939
3        4 2024-01-01 03:00:00   mobile              1          0        0
4        5 2024-01-01 04:00:00   mobile              1          0        0

#2. Understand Data

In [ ]:
df.info()
df.describe()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   user_id        1000 non-null   int64
 1   visit_date     1000 non-null   datetime64[ns]
 2   device         1000 non-null   object
 3   added_to_cart  1000 non-null   int64
 4   purchased      1000 non-null   int64
 5   revenue        1000 non-null   int64
dtypes: datetime64[ns](1), int64(4), object(1)
memory usage: 47.0+ KB

user_id          0
visit_date       0
device           0
added_to_cart    0
purchased        0
revenue          0
dtype: int64

#3. Clean Data

In [ ]:
df['visit_date'] = pd.to_datetime(df['visit_date'])
df = df.drop_duplicates()

     user_id          visit_date   device  added_to_cart  purchased  revenue
0          1 2024-01-01 00:00:00   mobile              0          0        0
1          2 2024-01-01 01:00:00  desktop              1          0        0
2          3 2024-01-01 02:00:00  desktop              1          1      939
3          4 2024-01-01 03:00:00   mobile              1          0        0
4          5 2024-01-01 04:00:00   mobile              1          0        0
..       ...                 ...      ...            ...        ...      ...
995      996 2024-02-11 11:00:00   mobile              1          1      291
996      997 2024-02-11 12:00:00  desktop              1          0        0
997      998 2024-02-11 13:00:00   mobile              0          0        0
998      999 2024-02-11 14:00:00  desktop              0          0        0
999     1000 2024-02-11 15:00:00   mobile              0          0        0

[1000 rows x 6 columns]

#4. Funnel Metrics

In [ ]:
total_users = df['user_id'].nunique()
cart_users = df[df['added_to_cart'] == 1]['user_id'].nunique()
buyers = df[df['purchased'] == 1]['user_id'].nunique()

cart_rate = cart_users / total_users
purchase_rate = buyers / total_users

print(cart_rate, purchase_rate)

0.615 0.309

#5. Drop-off Analysis

In [ ]:
drop_off = cart_users - buyers
print(drop_off)

306

#6. Device-Level Insights

In [ ]:
df.groupby('device').agg({
    'added_to_cart':'mean',
    'purchased':'mean'
})

         added_to_cart  purchased
device
desktop       0.635417   0.319444
mobile        0.606742   0.304775